spring:
  thymeleaf:
    cache: false

  web:
    resources:
      chain:
        cache: false
      cache:
        period: 0

  r2dbc:
    url: r2dbc:mysql://localhost:3306?serverZoneId=Asia/Shanghai
    password: 860226
    username: qiuli
    name: test
    pool:
      enabled: true
      min-idle: 5
      max-size: 10
      initial-size: 5

logging:
  level:
    root: info
    web: debug
    io.r2dbc: debug
    io.asyncer.r2dbc.mysql.QUERY: debug

server:
  compression:
    enabled: true